name: "issue maker"

description: "create an issue with a cat fact as a body"

inputs:
  issueTitle:
    description: "A name for the cat-fact issue"
    required: true
    default: "A cat fact 4 u"
    
  catFact:
    description: "the cat fact retreived from a previous action"
    required: true
    default: "Mona is an Octocat"
    
  repoToken:
    description: "Authentification token, use secrets.GITHUB_TOKEN"
    required: true
    
runs:
  using: "docker"
  image: "Dockerfile"
